name: Setup Node + pnpm + install
description: Reusable setup for Node and pnpm with cached install
inputs:
  node-version:
    description: The Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: https://registry.npmjs.org
    - shell: bash
      run: |
        pnpm install --frozen-lockfile --ignore-scripts
        pnpm -r rebuild