name: Build, Lint, and Test
description: A composite action to build, lint, and test the project
runs:
  using: composite
  steps:
    - name: Build packages
      shell: bash
      run: pnpm -r build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        if-no-files-found: error
        retention-days: 1
        path: packages/*/dist/

    - name: Lint code
      shell: bash
      run: pnpm -r lint

    - name: Run tests
      shell: bash
      run: pnpm -r test